// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yknycgpihtvfnawwtmfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrbnljZ3BpaHR2Zm5hd3d0bWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTExNTksImV4cCI6MjA1ODg2NzE1OX0.5QmUXzNfshOoVouXMJkPTOx8ed1jjXEhDWflIC1q7dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);